### ISSUE TITLE
error running ddseeker.py

### ISSUE THREAD

**Issue by ibseq** [cgplab/ddSeeker#2]
Hi everybody, 
I got the error below when runnign ddseeker on surecell data: what does it mean? I also repeated it with -c 20. I have an output generated but itd oesnt look good (sample1.bam). 
 
python ddSeeker.py --input ../../../Users/ibassano/Desktop/IGF112139/ddseq1_S1_L001_R1_001.fastq.gz ../../../Users/ibassano/Desktop/IGF112139/ddseq1_S1_L001_R2_001.fastq.gz --output sample1.bam --cores 4
[08:48:34] INFO - Extracting tags.
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "ddSeeker.py", line 78, in get_tags
    alignment = _local_aligner(sequence, linker, -2, -1)[0]
IndexError: list index out of range
"""
 
The above exception was the direct cause of the following exception:
 
Traceback (most recent call last):
  File "ddSeeker.py", line 319, in <module>
    main()
  File "ddSeeker.py", line 225, in main
    for (i, tags) in enumerate(pool.imap(get_tags, in_seqs1), 1):
  File "/anaconda3/lib/python3.6/multiprocessing/pool.py", line 761, in next
    raise value
IndexError: list index out of range

**Comment by romagnolid** [comment]
Hi, can you first try again using `python3`?

**Comment by ibseq** [comment]
Hi Dario, 
Same as before:

(base) wmnd-ibassano:Basespace_ddseq_analysis ibassano$ python3 /BCR_Tools/ddSeeker/ddSeeker.py --input ddseq1_S1_L001_R1_001.fastq.gz ddseq1_S1_L001_R2_001.fastq.gz --output sample1.bam --cores 20
[12:31:32] INFO - Extracting tags.
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/BCR_Tools/ddSeeker/ddSeeker.py", line 78, in get_tags
    alignment = _local_aligner(sequence, linker, -2, -1)[0]
IndexError: list index out of range
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/BCR_Tools/ddSeeker/ddSeeker.py", line 319, in <module>
    main()
  File "/BCR_Tools/ddSeeker/ddSeeker.py", line 225, in main
    for (i, tags) in enumerate(pool.imap(get_tags, in_seqs1), 1):
  File "/anaconda3/lib/python3.6/multiprocessing/pool.py", line 761, in next
    raise value
IndexError: list index out of range
(base) wmnd-ibassano:Basespace_ddseq_analysis ibassano$

**Comment by romagnolid** [comment]
OK, I'll check if there are any differences between python 3.5 (that I used) and python 3.6 as you appear to be using.
Meanwhile can you try using only one core?

**Comment by ibseq** [comment]
Same error

(base) wmnd-ibassano:Trimmed data ibassano$ python3 /BCR_Tools/ddSeeker/ddSeeker.py --input ddseq2_S2_L001_R1_001.fastq.gz ddseq2_S2_L001_R2_001.fastq.gz  --output sample2.bam --cores 1
[13:22:40] INFO - Extracting tags.
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/BCR_Tools/ddSeeker/ddSeeker.py", line 78, in get_tags
    alignment = _local_aligner(sequence, linker, -2, -1)[0]
IndexError: list index out of range
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/BCR_Tools/ddSeeker/ddSeeker.py", line 319, in <module>
    main()
  File "/BCR_Tools/ddSeeker/ddSeeker.py", line 225, in main
    for (i, tags) in enumerate(pool.imap(get_tags, in_seqs1), 1):
  File "/anaconda3/lib/python3.6/multiprocessing/pool.py", line 761, in next
    raise value
IndexError: list index out of range
(

**Comment by tmy12** [comment]
Hi!

I also got the same error when using Python 3.7.2.   

[09:44:47] INFO - Extracting tags.
[10:59:29] INFO - 1000000 reads processed.
[12:16:40] INFO - 2000000 reads processed.
[13:32:48] INFO - 3000000 reads processed.
[14:47:16] INFO - 4000000 reads processed.
[16:00:49] INFO - 5000000 reads processed.
[17:14:57] INFO - 6000000 reads processed.
[18:29:07] INFO - 7000000 reads processed.
[19:49:37] INFO - 8000000 reads processed.
[21:06:50] INFO - 9000000 reads processed.
[22:30:05] INFO - 10000000 reads processed.
[23:48:14] INFO - 11000000 reads processed.
[01:13:25] INFO - 12000000 reads processed.
[02:30:06] INFO - 13000000 reads processed.
[03:47:38] INFO - 14000000 reads processed.
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/anaconda3/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "./ddSeeker.py", line 78, in get_tags
    alignment = _local_aligner(sequence, linker, -2, -1)[0]
IndexError: list index out of range
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./ddSeeker.py", line 319, in <module>
    main()
  File "./ddSeeker.py", line 225, in main
    for (i, tags) in enumerate(pool.imap(get_tags, in_seqs1), 1):
  File "/anaconda3/lib/python3.7/multiprocessing/pool.py", line 748, in next
    raise value
IndexError: list index out of range

**Comment by ibseq** [comment]
Hi
do you know if this can be fixed at all?
I don’t understand what the issue is...

thank you 
BW
Irene

**Comment by romagnolid** [comment]
OK, so far I haven't encountered errors even using Python 3.7
It's strange that @tmy12's file stopped only after so many reads processed while @ibseq's didn't even start.

@tmy12 could you tell me how many reads are there in that fastq file?

@ibseq could you send me the first lines of your fastq files and attach them here? 
```
zcat ddseq1_S1_L001_R1_001.fastq.gz | head -100 > outfile1.fastq
zcat ddseq1_S1_L001_R2_001.fastq.gz | head -100 > outfile2.fastq
```

**Comment by romagnolid** [comment]
Could you also try using our test dataset?
https://github.com/cgplab/ddSeeker_example_dataset
To make it faster use the `--subset` option:
`ddSeeker.py -i file1.fastq.gz file2.fastq.gz -o output.bam -c 20 --subset 10000`

**Comment by tmy12** [comment]
There were ~30M reads in the file.  I also ran the program using another set of data with about 25M reads and it ran without a problem.  So, it looks like it might be related to that particular set of fastq files.

**Comment by BioInfoUCI** [comment]
Hello,

I've encountered the same problem. Same error message.
Each of my samples has about 40 million reads and I am using python 3.6. 
Can this be fixed?

Thanks!

**Comment by ibseq** [comment]
Hi Dario
my error was not because of your script: I sent the fastq data to Illumina and it seems that the barcodes have not been recovered , I only had 89 barcodes. 

I am repeating the experiment and I will try again

Thanks for the help
ibseq

**Comment by romagnolid** [comment]
Hello @ibseq, thanks for your update, I suspect everybody else may have similar problems.

**Comment by romagnolid** [comment]
Hello @BioInfoUCI, 
Is any read being processed or does the analysis stop immediately?

**Comment by BioInfoUCI** [comment]
Hello!

It stops immediately.

Thanks!

**Comment by romagnolid** [comment]
@BioInfoUCI Ok, could you send me the first few lines of your fastq files and attach them here?
I'm trying to figure out how to circumvent the error.

**Comment by BioInfoUCI** [comment]
S1_cat_R1.fastq.gz
<https://drive.google.com/file/d/1orFjUJ8tk3dQtLONnLdzClSyz4f-8bxJ/view?usp=drive_web>
 S1_cat_R2.fastq.gz
<https://drive.google.com/file/d/1YMSIQ8S7xt9F6iEpeJprNXAD-2gNjGTo/view?usp=drive_web>
I am attaching R1 and R2 for one of the samples.

Thank you!

**Comment by romagnolid** [comment]
Hello @BioInfoUCI, thank you for providing the files. The issue should be fixed now.

**Comment by BioInfoUCI** [comment]
Hello there,

The error still persists.

**Comment by romagnolid** [comment]
Are you using the same file you sent me? Is it the same IndexError? Does it process any read before stopping?

Update: I was able to analyze the entire fastq pair without issues.

**Comment by BioInfoUCI** [comment]
Hello,

Same file and same error. It doesn't process any reads...
Thanks!

**Comment by romagnolid** [comment]
OK, can you check if we are using the same ddseeker version?

    ddseeker.py --version

**Comment by romagnolid** [comment]
Due to lack of feedback I'm closing this issue for now.

**Comment by romagnolid** [comment]
Due to lack of feedback I'm closing this issue for now.
